fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.13.1"
    archive:
      repo: "https://github.com/voxpupuli/puppet-archive.git"
      ref: "v1.3.0"
  symlinks:
    sensu_wrapper: "#{source_dir}"
